config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'municipies#index'

  resources :municipies, except: %i[destroy show] do
    member do
      post :inactive
    end
    resources :citizens, except: %i[destroy show] do
      member do
        post :address
      end
    end
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :citizen
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
# frozen_string_literal: true

class Citizen < ApplicationRecord
  belongs_to :municipy, class_name: 'Municipy'
  has_one_attached :photo

  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  validates :name, presence: true
  validates :phone, presence: true

  validate :cns_validator
  validate :cpf_validator
  validate :birthday?
  validates :email, format: URI::MailTo::EMAIL_REGEXP

  def cpf_validator
    errors.add(:cpf, :invalid) unless CPF.valid?(cpf)
  end

  def cns_validator
    errors.add(:cns, :invalid) unless CnsValidator.new.valida_cns(cns)
  end

  def birthday?
    return false if birthday.blank?

    errors.add(:birthday, 'must be possible') unless birthday > (Date.current - 150.years)
  end
end

app/models/municipy.rb
# frozen_string_literal: true

class Municipy < ApplicationRecord
  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  validates :name, presence: true
end

app/controllers/address_controller.rb
# frozen_string_literal: true

class AddressController < ApplicationController
  def create
    Adrress.create!(upsert_params)
    render json: {}, status: :created
  end


  private

  def upsert_params
    params.require(:address)
          .permit(:zip_code, :street, :complement, :neighborhood, :city, :state, :ibge_code)
          .merge(municipy_id: params[:municipy_id], id: params[:id]).compact_blank
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/citizens_controller.rb
# frozen_string_literal: true

class CitizensController < ApplicationController
  def index
    search = Search::ElasticRepository.search(search_params[:name_start])
    @citizens = CitizenAdapter.from_elastic(search)
  end

  def new
    @municipy = Municipy.find(params[:municipy_id])
    @citizen = Citizen.new(municipy: @municipy)
  end

  def edit
    @municipy = Municipy.find(params[:municipy_id])
    @citizen = CitizensQuery.call(params: { id: params[:id] }).first
  end

  def create
    Citizens::UpsertUseCase.call(upsert_params)

    redirect_citizens_index
  end

  def update
    Citizens::UpsertUseCase.call(upsert_params)

    redirect_citizens_index
  end

  def inactive
    Citizens::InactiveUseCase.call(params[:id])

    redirect_citizens_index
  end

  private

  def redirect_citizens_index
    redirect_to municipy_citizens_url(params[:municipy_id])
  end

  def upsert_params
    params.require(:citizen)
          .permit(:name, :status, :cpf, :cns, :email, :birthday, :phone, :photo, :municipy_id)
          .merge(municipy_id: params[:municipy_id], id: params[:id]).compact_blank
  end

  def search_params
    params.permit(:name_start).merge(order: 'name_asc')
  end
end

app/controllers/municipies_controller.rb
# frozen_string_literal: true

class MunicipiesController < ApplicationController
  def index
    @municipies = MunicipiesQuery.call(params: search_params)
  end

  def new
    @municipy = Municipy.new
  end

  def edit
    @municipy = MunicipiesQuery.call(params: { id: params[:id] }).first
  end

  def create
    Municipies::UpsertUseCase.call(upsert_params)

    redirect_to root_path
  end

  def update
    Municipies::UpsertUseCase.call(upsert_params)

    redirect_to root_path
  end

  def inactive
    Municipies::InactiveUseCase.call(params[:id])

    redirect_to root_path
  end

  private

  def upsert_params
    params.require(:municipy).permit(:name, :status).merge(id: params[:id]).compact_blank
  end

  def search_params
    params.permit(:name_start).merge(order: 'name_asc')
  end
end

app/views/citizens/_form.html.erb
<div class="main w-max m-auto mt-10">
  <h2 class="text-2xl mb-6">New Citizen</h2>

  <%= form_for([@municipy, @citizen]) do |f| %>
    <div class="flex rounded text-gray-500 mb-4">
      <%= f.text_field :name, autofocus: true, autocomplete: "name",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "name of citizen"
      %>
    </div>
    <div class="flex rounded text-gray-500 mb-4">
      <%= f.number_field :cpf, autofocus: true, autocomplete: "cpf",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "cpf of citizen"
      %>
    </div>

    <div class="flex rounded text-gray-500 mb-4">
      <%= f.text_field :cns, autofocus: true, autocomplete: "cns",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "cns of citizen"
      %>
    </div>

    <div class="flex rounded text-gray-500 mb-4">
      <%= f.email_field :email, autofocus: true, autocomplete: "email",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "email of citizen"
      %>
    </div>

    <div class="flex rounded text-gray-500 mb-4">
      <%= f.date_field :birthday, autofocus: true, autocomplete: "birthday",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "birthday of citizen"
      %>
    </div>

    <div class="flex rounded text-gray-500 mb-4">
      <%= f.text_field :phone, autofocus: true, autocomplete: "phone",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "phone of citizen"
      %>
    </div>

    <div class="flex rounded text-gray-500 mb-4">
      <%= f.file_field :photo, autofocus: true, autocomplete: "photo",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "photo of citizen"
      %>
    </div>

    <% unless @citizen.new_record? %>
    <div class="flex rounded text-gray-500 mb-4">
      <%= f.select(:status, Citizen.statuses, :prompt => 'Select') %>
    </div>
    <% end %>

    <div class="actions">
      <%= f.submit "Save", class: "rounded mt-6 px-4 bg-blue-500" %>
    </div>
  <% end %>
</div>

app/views/citizens/_list.html.erb
<form action="citizens">
  <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
    <div class="sm:col-span-4">
      Search: <input type="text" name="name_start" placeholder="Search citizens" class="bg-gray-100 text-sm text-gray-800 transition border focus:outline-none focus:border-gray-700 rounded py-1 px-2 pl-10 appearance-none leading-normal">
    </div>
  </div>
</form>

<table class="w-full p-5 text-gray-700">
  <thead>
    <tr>
      <th class="text-left text-blue-900">Photo</th>
      <th class="text-left text-blue-900">Name</th>
      <th class="text-left text-blue-900">Status</th>
      <th class="text-left text-blue-900">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @citizens.each do |citizen| %>
    <tr>
      <td><%= citizen.photo.attached? ? image_tag(citizen.photo.variant(resize_to_limit: [200, 200])) : nil %></td>
      <td><%= citizen.name %></td>
      <td><%= citizen.status %></td>
      <td class="flex flex-row">
        <%= link_to('Edit', edit_municipy_citizen_path(citizen.municipy_id, citizen.id), class: "rounded mt-6 px-4 bg-blue-300") %>
        <%= link_to "show modal", address_municipy_citizen_path(citizen.municipy_id, citizen.id), remote: true %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/citizens/edit.html.erb
<div class="w-full p-3">
  <div class="bg-white border rounded shadow">
    <div class="border-b p-3">
      <h5 class="font-bold uppercase text-gray-600">Citizens</h5>
    </div>
    <div class="p-5">
      <%= render('form') %>
    </div>
  </div>
</div>

app/views/citizens/index.html.erb
<div class="w-full p-3">
  <!--Table Card-->
  <div class="bg-white border rounded shadow">
    <div class="border-b p-3">
      <h5 class="font-bold uppercase text-gray-600">Citizens</h5>
    </div>
    <div class="p-5">
      <%= render('list') %>
    </div>
    <div class="p-5">
      <%= link_to('New citizen', new_municipy_citizen_path, class: "rounded mt-6 px-4 bg-green-300") %>
    </div>
  </div>
  <!--/table Card-->
</div>

app/views/citizens/new.html.erb
<div class="w-full p-3">
  <div class="bg-white border rounded shadow">
    <div class="border-b p-3">
      <h5 class="font-bold uppercase text-gray-600">Citizens</h5>
    </div>
    <div class="p-5">
      <%= render('form') %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>MunicipiesCensus</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <nav id="header" class="bg-white fixed w-full z-10 top-0 shadow">
      <div class="w-full container mx-auto flex flex-wrap items-center mt-0 pt-3 pb-3 md:pb-0">

        <div class="w-1/2 pl-2 md:pl-1">
          <a class="text-gray-900 text-base xl:text-xl no-underline hover:no-underline font-bold " href="<%= root_path %>">
            <i class="fas fa-sun text-pink-600 pr-3"></i>
            <%= t('hello') %>
          </a>
        </div>
        <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-white z-20" id="nav-content">
          <ul class="list-reset lg:flex flex-1 items-center px-4 md:px-0">
            <li class="mr-6 my-2 md:my-0">
              <a href="<%= municipies_path %>" class="block py-1 md:py-3 pl-1 align-middle text-pink-600 no-underline hover:text-gray-900 border-b-2 border-orange-600 hover:border-orange-600">
                <i class="fas fa-home fa-fw mr-3 text-pink-600"></i><span class="pb-1 md:pb-0 text-sm">Home</span>
              </a>
            </li>
          </ul>

          <div class="relative pull-right pl-4 pr-4 md:pr-0">
            <form action="municipies">
              <input type="text" name="name_start" placeholder="Search municipies" class="w-full bg-gray-100 text-sm text-gray-800 transition border focus:outline-none focus:border-gray-700 rounded py-1 px-2 pl-10 appearance-none leading-normal">
            </form>
            <div class="absolute search-icon" style="top: 0.375rem;left: 1.75rem;">
              <svg class="fill-current pointer-events-none text-gray-800 w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
              </svg>
            </div>
          </div>

        </div>

      </div>
    </nav>

    <!--Container-->
    <div class="container w-full mx-auto pt-10">
      <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">
      <!--Console Content-->
      <div class="flex flex-wrap">
        <div class="flex flex-row flex-wrap flex-grow mt-2">
          <%= yield %>
        </div>
        <!--/ Console Content-->
      </div>
    </div>
    <!--/container-->

    <footer class="bg-white border-t border-gray-400 shadow">
      <div class="container max-w-md mx-auto flex py-8">
      </div>
    </footer>
  </body>
</html>

app/views/municipies/_form.html.erb
<div class="main w-max m-auto mt-10">
  <h2 class="text-2xl mb-6">New Municipy</h2>

  <%= form_for(@municipy) do |f| %>
    <div class="flex rounded text-gray-500 mb-4">
      <%= f.text_field :name, autofocus: true, autocomplete: "name",
        class: "outline-none px-4 h-full py-2 text-lg",
        placeholder: "name of municipy"
      %>
    </div>

    <% unless @municipy.new_record? %>
    <div class="flex rounded text-gray-500 mb-4">
      <%= f.select(:status, Municipy.statuses, :prompt => 'Select') %>
    </div>
    <% end %>

    <div class="actions">
      <%= f.submit "Save", class: "rounded mt-6 px-4 bg-blue-500" %>
    </div>
  <% end %>
</div>

app/views/municipies/_list.html.erb
<table class="w-full p-5 text-gray-700">
  <thead>
    <tr>
      <th class="text-left text-blue-900">Name</th>
      <th class="text-left text-blue-900">Status</th>
      <th class="text-left text-blue-900">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @municipies.each do |municipy| %>
    <tr>
      <td><%= municipy.name %></td>
      <td><%= municipy.status %></td>
      <td class="flex flex-row">
        <%= link_to('Edit', edit_municipy_path(municipy.id), class: "rounded mt-6 px-4  mx-4 bg-blue-300") %>
        <%= form_for :municipy, url: inactive_municipy_path(municipy.id), method: :post do |f|%>
          <%= f.submit "Inactive", class: "rounded mt-6 px-4 mx-4 bg-red-500" %>
        <%end%>
        <%= link_to('Citizens', municipy_citizens_path(municipy.id), class: "rounded mt-6 px-4 mx-4 bg-blue-300") %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/municipies/edit.html.erb
<div class="w-full p-3">
  <div class="bg-white border rounded shadow">
    <div class="border-b p-3">
      <h5 class="font-bold uppercase text-gray-600">Municipies</h5>
    </div>
    <div class="p-5">
      <%= render('form') %>
    </div>
  </div>
</div>

app/views/municipies/index.html.erb
<div class="w-full p-3">
  <!--Table Card-->
  <div class="bg-white border rounded shadow">
    <div class="border-b p-3">
      <h5 class="font-bold uppercase text-gray-600">Municipies</h5>
    </div>
    <div class="p-5">
      <%= render('list') %>
    </div>
    <div class="p-5">
      <%= link_to('New municipy', new_municipy_path, class: "rounded mt-6 px-4 bg-green-300") %>
    </div>
  </div>
  <!--/table Card-->
</div>

app/views/municipies/new.html.erb
<div class="w-full p-3">
  <div class="bg-white border rounded shadow">
    <div class="border-b p-3">
      <h5 class="font-bold uppercase text-gray-600">Municipies</h5>
    </div>
    <div class="p-5">
      <%= render('form') %>
    </div>
  </div>
</div>